[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths     = ["src/tests"]
python_files  = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-timeout",
    "pytest-order",
    "Faker",
    "psycopg2-binary",
]